### PR TITLE
MTL-2229 add boot order

### PR DESCRIPTION
**Pull request by jacobsalmela**
### Summary and Scope

- Requires: https://github.com/Cray-HPE/csm-redfish-interface-emulator/pull/8

#### Issue Type

- RFE Pull Request

### CODE REVIEW

**Review by rustydb — APPROVED** [review]

**Comment by rustydb** [comment]
This works for gigabyte, but not intel or hpe.

```bash
(crucible) [547]rusty@HPE-XHD22YD7DW:~/gitstuffs/cray-shasta/gru> ./gru --insecure show boot surtur-ncn-m001-mgmt.hpc.amslabs.hpecorp.net
Asynchronously querying [    1] hosts ... 
surtur-ncn-m001-mgmt.hpc.amslabs.hpecorp.net:
        ERROR: 404: {"error":{"code":"iLO.0.10.ExtendedInfo","message":"See @Message.ExtendedInfo for more information.","@Message.ExtendedInfo":[{"MessageArgs":["/redfish/v1/Systems/1/BootOptions/0013"],"MessageId":"Base.1.4.ResourceMissingAtURI"}]}}
(crucible) [548]rusty@HPE-XHD22YD7DW:~/gitstuffs/cray-shasta/gru> ./gru --insecure show boot redbull-ncn-m001-mgmt.hpc.amslabs.hpecorp.net
Asynchronously querying [    1] hosts ... 
panic: interface conversion: interface {} is nil, not []interface {}

goroutine 18 [running]:
github.com/Cray-HPE/gru/pkg/cmd/cli/boot.getBootInformation({0x16b9b74eb?, 0x0?}, {0x0?, 0x0?, 0x0?})
        /Users/rusty/gitstuffs/cray-shasta/gru/pkg/cmd/cli/boot/show.go:125 +0x8e4
github.com/Cray-HPE/gru/pkg/query.Async.func1({0x16b9b74eb, 0x2d}, {0x0?, 0x0?, 0x0?})
        /Users/rusty/gitstuffs/cray-shasta/gru/pkg/query/query.go:56 +0x6c
created by github.com/Cray-HPE/gru/pkg/query.Async
        /Users/rusty/gitstuffs/cray-shasta/gru/pkg/query/query.go:53 +0xbc
(crucible) [549]rusty@HPE-XHD22YD7DW:~/gitstuffs/cray-shasta/gru> git status
On branch driven-snake-eyes
Your branch is up to date with 'origin/driven-snake-eyes'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   go.mod

no changes added to commit (use "git add" and/or "git commit -a")
(crucible) [550]rusty@HPE-XHD22YD7DW:~/gitstuffs/cray-shasta/gru> ./gru --insecure show boot drax-ncn-m001-mgmt.hpc.amslabs.hpecorp.net
Asynchronously querying [    1] hosts ... 
drax-ncn-m001-mgmt.hpc.amslabs.hpecorp.net:
        Order               : [map[Boot0006:UEFI: PXE IP4 Mellanox Network Adapter - B8:59:9F:C7:12:F2] map[Boot0008:UEFI: PXE IP4 Mellanox Network Adapter - B8:59:9F:C7:12:F3] map[Boot000D:UEFI: HTTP IP4 Mellanox Network Adapter - B8:59:9F:C7:12:F2] map[Boot000E:UEFI: HTTP IP4 Mellanox Network Adapter - B8:59:9F:C7:12:F3] map[Boot000F:UEFI: HTTP IP4 Intel(R) I350 Gigabit Network Connection] map[Boot0011:UEFI: HTTP IP4 Intel(R) I350 Gigabit Network Connection] map[Boot0015:UEFI: PXE IP6 Intel(R) I350 Gigabit Network Connection] map[Boot0016:UEFI: PXE IP6 Intel(R) I350 Gigabit Network Connection] map[Boot0010:UEFI: PXE IP4 Intel(R) I350 Gigabit Network Connection] map[Boot0012:UEFI: PXE IP4 Intel(R) I350 Gigabit Network Connection] map[Boot0013:UEFI: PXE IP6 Mellanox Network Adapter - B8:59:9F:C7:12:F2] map[Boot0014:UEFI: PXE IP6 Mellanox Network Adapter - B8:59:9F:C7:12:F3] map[Boot000A:UEFI OS] map[Boot000B:UEFI OS] map[Boot000C:UEFI OS] map[Boot0009:UEFI: Built-in EFI Shell]]
        Next                : 
(crucible) [552]rusty@HPE-XHD22YD7DW:~/gitstuffs/cray-shasta/gru> ./gru --version
gru version 0.0.4~23~g7ab443a
```

**Comment by jacobsalmela** [comment]
Never got to the tests for this PR..

I think it ties back to the messy print thing we have going on.  You had something in the works with that?

**Comment by rustydb** [comment]
Yeah, that's all smoothed over in #32 . At present, I'm going through all the existing commands and verifying they work as expected, as well as updating the tests.

**Comment by jacobsalmela** [comment]
Ok.  The simulator won't catch everything.  Especially any write ops.

**Pull request merged**
